import { useCallback, useEffect, useRef, useState } from "react";
import type { ApiRequest } from "./shared/request";
import { ApiError, requestJson } from "./shared/request";
import { Badge, DefinitionList, EmptyState, ErrorState, LoadingState, PageHeader, formatValue } from "./shared/view";
import styles from "./SkillsPage.module.less";

type Diagnostic = string | { message?: string; description?: string };
type Skill = { id: string; name?: string; description?: string; scope?: string; origin?: string; source?: string; path?: string; mutable?: boolean; editable?: boolean; revision?: string; diagnostics?: Diagnostic[] };
type SkillsResponse = { skills?: Skill[]; items?: Skill[] };
type SkillDetail = { skill: Skill; content: string };

function isEditable(skill: Skill) { return skill.mutable === true || skill.editable === true; }

export default function SkillsPage({ request = requestJson, initialSkillId = "" }: { request?: ApiRequest; initialSkillId?: string }) {
  const [skills, setSkills] = useState<Skill[]>(); const [selected, setSelected] = useState(initialSkillId);
  const previousInitialSkillId = useRef(initialSkillId); const [detailRequest, setDetailRequest] = useState(0);
  const [detail, setDetail] = useState<SkillDetail>(); const [content, setContent] = useState(""); const [listError, setListError] = useState<unknown>(); const [detailError, setDetailError] = useState<unknown>(); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const loadList = useCallback(() => { setListError(undefined); request<SkillsResponse>("/api/skills").then((data) => setSkills(data.skills ?? data.items ?? []), setListError); }, [request]);
  useEffect(loadList, [loadList]);
  useEffect(() => { if (previousInitialSkillId.current === initialSkillId) return; previousInitialSkillId.current = initialSkillId; setSelected(initialSkillId); }, [initialSkillId]);
  useEffect(() => { if (!selected) { setDetail(undefined); setDetailError(undefined); return; } const controller = new AbortController(); setDetail(undefined); setDetailError(undefined); request<SkillDetail>(`/api/skills/${encodeURIComponent(selected)}`, { signal: controller.signal }).then((next) => { setDetail(next); setContent(next.content ?? ""); }, (reason) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setDetailError(reason); }); return () => controller.abort(); }, [detailRequest, request, selected]);
  const save = async () => { if (!detail?.skill.revision) return; setBusy(true); setNotice(""); try { await request(`/api/skills/${encodeURIComponent(detail.skill.id)}`, { method: "PUT", body: { content, revision: detail.skill.revision } }); setNotice("Skill saved."); const next = await request<SkillDetail>(`/api/skills/${encodeURIComponent(detail.skill.id)}`); setDetail(next); setContent(next.content); await loadList(); } catch (reason) { setNotice(reason instanceof ApiError && reason.status === 409 ? "Revision conflict: reload the latest content before saving." : reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const remove = async () => { if (!detail?.skill.revision || !window.confirm(`Delete skill “${detail.skill.name ?? detail.skill.id}”? This permanently deletes the authorized SKILL.md.`)) return; setBusy(true); setNotice(""); try { await request(`/api/skills/${encodeURIComponent(detail.skill.id)}`, { method: "DELETE", body: { revision: detail.skill.revision } }); setSelected(""); setDetail(undefined); setNotice("Skill deleted."); await loadList(); } catch (reason) { setNotice(reason instanceof ApiError && reason.status === 409 ? "Revision conflict: the skill changed before deletion." : reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  if (listError) return <ErrorState error={listError} retry={loadList} />;
  if (!skills) return <LoadingState />;
  return <main className={styles.page}><PageHeader title="Skills" description="Inspect effective skills and edit only resources authorized by the server." />{notice && <div className={styles.notice} role="status">{notice}</div>}
    <section className={styles.layout}><aside className={styles.list}>{skills.length ? skills.map((skill) => <button className={selected === skill.id ? styles.selected : ""} type="button" key={skill.id} onClick={() => setSelected(skill.id)}><span><strong>{skill.name ?? skill.id}</strong><Badge tone={isEditable(skill) ? "good" : "neutral"}>{isEditable(skill) ? "editable" : "read only"}</Badge></span><p>{skill.description ?? "No description"}</p><code>{skill.path ?? skill.id}</code><small>{skill.scope ?? "unknown"} · {skill.origin ?? "top-level"} · {skill.source ?? "unknown"}</small>{Boolean(skill.diagnostics?.length) && <Badge tone="warn">{skill.diagnostics?.length} diagnostics</Badge>}</button>) : <EmptyState>No skills found in the configured roots.</EmptyState>}</aside>
      <article className={styles.detail}>{!selected ? <EmptyState>Select a skill to inspect its details.</EmptyState> : detailError ? <ErrorState error={detailError} retry={() => setDetailRequest((value) => value + 1)} /> : !detail ? <LoadingState label="Loading skill…" /> : <><header><div><h2>{detail.skill.name ?? detail.skill.id}</h2><p>{detail.skill.description ?? "Skill detail"}</p></div><Badge tone={isEditable(detail.skill) ? "good" : "neutral"}>{isEditable(detail.skill) ? "editable" : "read only"}</Badge></header><textarea aria-label="Skill Markdown content" value={content} readOnly={!isEditable(detail.skill)} onChange={(event) => setContent(event.target.value)} spellCheck={false} />{isEditable(detail.skill) && <div className={styles.actions}><button type="button" disabled={busy || content === detail.content} onClick={() => void save()}>Save revision</button><button className={styles.danger} type="button" disabled={busy} onClick={() => void remove()}>Delete skill</button></div>}<section className={styles.metadata}><div><h3>Resource</h3><DefinitionList values={{ ID: detail.skill.id, Scope: detail.skill.scope, Origin: detail.skill.origin, Source: detail.skill.source, Path: detail.skill.path, Revision: detail.skill.revision }} /></div><div><h3>Diagnostics</h3>{detail.skill.diagnostics?.length ? <ul>{detail.skill.diagnostics.map((item, index) => <li key={index}>{typeof item === "string" ? item : item.message ?? item.description ?? formatValue(item)}</li>)}</ul> : <p>No diagnostics reported.</p>}</div></section></>}</article>
    </section></main>;
}
