import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import planCore from "../lib/plan-core.cjs";
const core=planCore as any; const WRITE=new Set(["edit","write"]);
export default function(pi:ExtensionAPI){let enabled=false,previous:string[]|undefined,plan:any[]=[],explanation:string|undefined;
 const save=()=>pi.appendEntry("pi-sdlc-plan",{enabled,toolsBeforePlanMode:previous,plan,explanation});
 const ui=(ctx:ExtensionContext)=>{ctx.ui.setStatus("pi-sdlc-plan",enabled?ctx.ui.theme.fg("warning","⏸ plan"):plan.length?ctx.ui.theme.fg("accent",`📋 ${plan.filter(x=>x.status==="completed").length}/${plan.length}`):undefined);const lines=plan.slice(0,5).map(x=>`${x.status==="completed"?"✓":x.status==="in_progress"?"●":x.status==="blocked"?"!":"○"} ${x.step}`);if(plan.length>5)lines.push(`… +${plan.length-5} more`);ctx.ui.setWidget("pi-sdlc-plan",lines.length?lines:undefined);};
 pi.registerTool({name:"update_plan",label:"Update plan",description:"Update the session-visible plan and progress; does not authorize implementation.",parameters:Type.Object({explanation:Type.Optional(Type.String()),plan:Type.Array(Type.Object({id:Type.String(),step:Type.String(),status:Type.Union([Type.Literal("pending"),Type.Literal("in_progress"),Type.Literal("completed"),Type.Literal("blocked")])}),{minItems:1,maxItems:20})}),async execute(_id,args,_signal,_update,ctx){try{plan=core.validatePlan(args.plan,args.explanation,plan);explanation=args.explanation?.trim()||undefined;save();ui(ctx);return{content:[{type:"text",text:`Plan updated: ${plan.filter((x:any)=>x.status==="completed").length}/${plan.length} completed.`}],details:{plan,explanation}};}catch(e){return{content:[{type:"text",text:`Plan update rejected: ${String(e)}`}],details:{},isError:true};}}});
 pi.registerCommand("plan",{description:"Enter read-only collaborative planning mode (/plan off | /plan status)",getArgumentCompletions:p=>["off","status"].filter(x=>x.startsWith(p)).map(value=>({value,label:value})),handler:async(args,ctx)=>{const a=core.parsePlanArgs(args);if(a.error)return ctx.ui.notify(a.error,"warning");if(a.action==="status")return ctx.ui.notify(`pi-sdlc: plan mode ${enabled?"enabled":"disabled"}; ${plan.length} plan steps.`,"info");if(a.action==="off"){if(enabled){pi.setActiveTools(previous??pi.getActiveTools());enabled=false;previous=undefined;save();ui(ctx);}return ctx.ui.notify("pi-sdlc: plan mode disabled; this is not implementation approval.","info");}if(!ctx.isIdle())return ctx.ui.notify("pi-sdlc: /plan must be entered while idle.","warning");if(!enabled){previous=pi.getActiveTools();pi.setActiveTools([...core.PLAN_TOOLS,"update_plan"]);enabled=true;save();ui(ctx);}ctx.ui.notify("pi-sdlc: plan mode enabled (read-only; /plan off exits).","info");}});
 pi.on("tool_call",async e=>{if(!enabled)return;if(WRITE.has(e.toolName))return{block:true,reason:"Plan mode is read-only."};if(e.toolName==="bash"&&!core.isReadOnlyBashCommand(String(e.input.command??"")))return{block:true,reason:"Plan mode only permits one allowlisted read-only bash command."};if(![...core.PLAN_TOOLS,"update_plan"].includes(e.toolName))return{block:true,reason:`Plan mode blocks ${e.toolName}.`};});
 pi.on("before_agent_start",async()=>enabled?{message:{customType:"pi-sdlc-plan-context",content:core.buildPlanPrompt(),display:false}}:undefined);
 pi.on("session_start",async(_e,ctx)=>{const e=ctx.sessionManager.getEntries().filter((x:any)=>x.type==="custom"&&x.customType==="pi-sdlc-plan").pop() as any;const s=core.normalizePlanState(e?.data);enabled=s.enabled;previous=s.toolsBeforePlanMode;plan=s.plan;explanation=s.explanation;if(enabled)pi.setActiveTools([...core.PLAN_TOOLS,"update_plan"]);ui(ctx);});
}
