import { test } from "node:test";
import assert from "node:assert/strict";
import { buildPlanPrompt,isReadOnlyBashCommand,normalizePlanState,parsePlanArgs,validatePlan } from "../packages/sdlc/lib/plan-core.cjs";
test("plan args",()=>{assert.deepEqual(parsePlanArgs(""),{action:"on"});assert.deepEqual(parsePlanArgs("off"),{action:"off"});assert.deepEqual(parsePlanArgs("status"),{action:"status"});assert.equal(parsePlanArgs("on").error,"usage: /plan [off|status]");});
test("allowlists bounded inspection",()=>{for(const x of ["pwd","ls -la src","rg -n TODO .","find packages -name package.json","sed -n 1,80p package.json","git status --short","git diff --cached","npm audit","npm --version","node --version"])assert.equal(isReadOnlyBashCommand(x),true,x);});
test("rejects writes and shell composition",()=>{for(const x of ["rm -rf /tmp/x","git commit -m x","npm install","npm test","echo hi > x","git status; rm -rf x","rg TODO | tee result","$(rm -rf x)","curl https://example.com","mkdir x"])assert.equal(isReadOnlyBashCommand(x),false,x);});
test("normalizes persisted state",()=>{assert.deepEqual(normalizePlanState({enabled:true,toolsBeforePlanMode:["read","bash","read"],plan:[{id:"a",step:"Inspect",status:"pending"}]}),{enabled:true,toolsBeforePlanMode:["read","bash"],plan:[{id:"a",step:"Inspect",status:"pending"}],explanation:undefined});});
test("validates structured plan state",()=>{const p=validatePlan([{id:"inspect",step:"Inspect evidence",status:"completed"},{id:"build",step:"Build feature",status:"in_progress"}]);assert.equal(p.length,2);assert.throws(()=>validatePlan([{id:"a",step:"a",status:"in_progress"},{id:"b",step:"b",status:"in_progress"}]),/only one/);assert.throws(()=>validatePlan([{id:"a",step:"a",status:"blocked"}]),/explanation/);assert.throws(()=>validatePlan([{id:"a",step:"a",status:"pending"},{id:"a",step:"b",status:"pending"}]),/unique/);assert.throws(()=>validatePlan([{id:"a",step:"a",status:"pending"}],undefined,[{id:"a",step:"a",status:"completed"}]),/completed/);});
test("prompt is proposal-only",()=>{const p=buildPlanPrompt();assert.match(p,/PLAN MODE/);assert.match(p,/do not execute/);assert.match(p,/update_plan/);assert.match(p,/not implementation approval/);});
