"use strict";
const PLAN_TOOLS=["read","grep","find","ls","bash"];
const SHELL_CONTROL=/[|;&><`\n\r]|\$\(|\$\{/;
const STATUSES=new Set(["pending","in_progress","completed","blocked"]);
function parsePlanArgs(input=""){const t=String(input).trim().split(/\s+/).filter(Boolean);if(!t.length)return{action:"on"};if(t.length===1&&["off","status"].includes(t[0]))return{action:t[0]};return{error:"usage: /plan [off|status]"};}
function isReadOnlyBashCommand(c){if(typeof c!=="string"||!c.trim()||SHELL_CONTROL.test(c))return false;const[a,...x]=c.trim().split(/\s+/);if(["cat","head","tail","wc","stat","file","pwd","ls","find","rg","grep","diff","du"].includes(a))return true;if(a==="sed")return x[0]==="-n";if(a==="node")return x.length===1&&x[0]==="--version";if(a==="git"){if(["status","log","diff","show","branch","remote","ls-files"].includes(x[0]))return true;return x[0]==="config"&&["--get","--get-regexp"].includes(x[1]);}return a==="npm"&&((x.length===1&&x[0]==="--version")||["list","ls","view","info","outdated","audit"].includes(x[0]));}
function normalizePlanState(v){if(!v||typeof v!=="object")return{enabled:false,toolsBeforePlanMode:undefined,plan:[]};const tools=Array.isArray(v.toolsBeforePlanMode)&&v.toolsBeforePlanMode.every(x=>typeof x==="string")?[...new Set(v.toolsBeforePlanMode)]:undefined;const plan=Array.isArray(v.plan)?v.plan.filter(s=>s&&typeof s.id==="string"&&typeof s.step==="string"&&STATUSES.has(s.status)).slice(0,20):[];return{enabled:v.enabled===true,toolsBeforePlanMode:tools,plan,explanation:typeof v.explanation==="string"?v.explanation:undefined};}
function validatePlan(plan,explanation,previous=[]){if(!Array.isArray(plan)||!plan.length||plan.length>20)throw Error("plan must contain 1-20 steps");const ids=new Set(),active=plan.filter(s=>s.status==="in_progress");if(active.length>1)throw Error("only one step may be in_progress");for(const s of plan){if(!s||typeof s.id!=="string"||!s.id.trim()||typeof s.step!=="string"||!s.step.trim()||!STATUSES.has(s.status)||ids.has(s.id))throw Error("each step needs a unique id, text, and valid status");ids.add(s.id);if(s.status==="blocked"&&!explanation?.trim())throw Error("blocked plans require an explanation");}const next=plan.map(s=>({id:s.id.trim(),step:s.step.trim(),status:s.status}));const nextById=new Map(next.map(s=>[s.id,s]));for(const old of Array.isArray(previous)?previous:[]){if(old?.status!=="completed")continue;const replacement=nextById.get(old.id);if((!replacement||replacement.status!=="completed")&&!explanation?.trim())throw Error("completed steps require an explanation before changing or removing them");}return next;}
function buildPlanPrompt(){return "You are in PLAN MODE: collaborate on a plan, but do not execute it. Use update_plan only when the evidence-based proposal materially changes. A plan update is not implementation approval.";}
module.exports={PLAN_TOOLS,parsePlanArgs,isReadOnlyBashCommand,normalizePlanState,validatePlan,buildPlanPrompt};
